//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicSqlEditor.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.0.0")] // Adjust version as needed
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        // Example setting:
        // [global::System.Configuration.UserScopedSettingAttribute()]
        // [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        // [global::System.Configuration.DefaultSettingValueAttribute("")]
        // public string LastUsedFilter {
        //     get {
        //         return ((string)(this["LastUsedFilter"]));
        //     }
        //     set {
        //         this["LastUsedFilter"] = value;
        //     }
        // }
    }
}